name: Commit Automático Personalizado

on:
  schedule:
    # Lunes, Miércoles, Jueves (todos los lunes, miércoles, jueves a las 10 AM UTC)
    - cron: '0 10 * * 1,3,4'
    # Martes (todas las semanas, pero controlamos en el script si es semana par)
    - cron: '0 10 * * 2'
    # Viernes (todas las semanas, pero controlamos si es semana múltiplo de 3)
    - cron: '0 10 * * 5'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Obtener fecha y lógica de commits
        id: commit-plan
        run: |
          DAY=$(date +%u)  # 1=Lunes, ..., 7=Domingo
          WEEK_NUM=$(date +%U)  # Semana del año (00-53)

          echo "Día: $DAY, Semana: $WEEK_NUM"

          COMMITS=0

          if [ "$DAY" = "1" ] || [ "$DAY" = "3" ] || [ "$DAY" = "4" ]; then
            COMMITS=3
          elif [ "$DAY" = "2" ]; then
            if [ $((WEEK_NUM % 2)) -eq 0 ]; then
              COMMITS=1
            fi
          elif [ "$DAY" = "5" ]; then
            if [ $((WEEK_NUM % 3)) -eq 0 ]; then
              COMMITS=1
            fi
          fi

          echo "Commits a hacer: $COMMITS"
          echo "commits=$COMMITS" >> $GITHUB_OUTPUT

      - name: Hacer commits
        if: steps.commit-plan.outputs.commits != '0'
        run: |
          for i in $(seq 1 ${{ steps.commit-plan.outputs.commits }}); do
            echo "Commit $i - $(date)" >> activity.txt
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add activity.txt
            git commit -m "Commit automático #$i - $(date)"
          done
          git push
