name: Commit Automático Avanzado

permissions:
  contents: write  # Permite hacer git push

on:
  schedule:
    # Lunes, Miércoles, Jueves
    - cron: '0 8 * * 1,3,4'
    # Martes (todas las semanas, validamos si es par)
    - cron: '0 8 * * 2'
    # Viernes (todas las semanas, validamos si es múltiplo de 3)
    - cron: '0 8 * * 5'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Obtener lógica de commits
        id: plan
        run: |
          DAY_NUM=$(date +%u)  # 1=Lunes, ..., 7=Domingo
          WEEK_NUM=$(date +%U)  # Semana del año (00-53)

          declare -a DAYS=(null monday tuesday wednesday thursday friday saturday sunday)
          DAY_NAME=${DAYS[$DAY_NUM]}

          COMMITS=0

          if [ "$DAY_NUM" = "1" ] || [ "$DAY_NUM" = "3" ] || [ "$DAY_NUM" = "4" ]; then
            COMMITS=3
          elif [ "$DAY_NUM" = "2" ]; then
            if [ $((WEEK_NUM % 2)) -eq 0 ]; then
              COMMITS=1
            fi
          elif [ "$DAY_NUM" = "5" ]; then
            if [ $((WEEK_NUM % 3)) -eq 0 ]; then
              COMMITS=1
            fi
          fi

          echo "Día: $DAY_NAME - Commits a hacer: $COMMITS"
          echo "commits=$COMMITS" >> $GITHUB_OUTPUT
          echo "day_name=$DAY_NAME" >> $GITHUB_OUTPUT

      - name: Hacer commits
        if: steps.plan.outputs.commits != '0'
        run: |
          FILE="activity-${{ steps.plan.outputs.day_name }}.txt"

          for i in $(seq 1 ${{ steps.plan.outputs.commits }}); do
            # Simular una hora aleatoria entre 8:00 y 18:00
            HOUR=$((RANDOM % 10 + 8))
            MINUTE=$((RANDOM % 60))
            DATE="$(date "+%Y-%m-%d") $HOUR:$(printf "%02d" $MINUTE)"

            echo "Commit $i a las $DATE - $RANDOM" >> "$FILE"
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add "$FILE"
            git commit -m "Commit automático #$i - $DATE"
          done

          git push origin HEAD
