name: Commit Automático Avanzado

permissions:
  contents: write  # Permitir commits y push

on:
  schedule:
    # Lunes, Miércoles, Jueves
    - cron: '0 8 * * 1,3,4'
    # Martes (todas las semanas, validamos si es par)
    - cron: '0 8 * * 2'
    # Viernes (todas las semanas, validamos si es múltiplo de 3)
    - cron: '0 8 * * 5'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Calcular commits del día
        id: plan
        run: |
          DAY_NUM=$(date +%u)  # 1=Lunes, ..., 7=Domingo
          WEEK_NUM=$(date +%U)  # Semana del año (00-53)

          declare -a DAYS=(null monday tuesday wednesday thursday friday saturday sunday)
          DAY_NAME=${DAYS[$DAY_NUM]}

          COMMITS=0

          # Lunes, miércoles, jueves → 3 commits
          if [ "$DAY_NUM" = "1" ] || [ "$DAY_NUM" = "3" ] || [ "$DAY_NUM" = "4" ]; then
            COMMITS=3
          # Martes → solo si la semana es par
          elif [ "$DAY_NUM" = "2" ]; then
            if [ $((WEEK_NUM % 2)) -eq 0 ]; then
              COMMITS=1
            fi
          # Viernes → solo si la semana es múltiplo de 3
          elif [ "$DAY_NUM" = "5" ]; then
            if [ $((WEEK_NUM % 3)) -eq 0 ]; then
              COMMITS=1
            fi
          fi

          echo "Día: $DAY_NAME - Commits a hacer: $COMMITS"
          echo "commits=$COMMITS" >> $GITHUB_OUTPUT
          echo "day_name=$DAY_NAME" >> $GITHUB_OUTPUT

      - name: Hacer commits automáticos
        if: ${{ steps.plan.outputs.commits != '0' && steps.plan.outputs.commits != '' }}
        run: |
          FILE="activity-${{ steps.plan.outputs.day_name }}.txt"

          # Configurar tu identidad (importante para que cuente como tuyo)
          git config user.name "JaironMark"
          git config user.email "123576109+JaironMark@users.noreply.github.com"

          # Crear commits según la lógica
          for i in $(seq 1 ${{ steps.plan.outputs.commits }}); do
            HOUR=$((RANDOM % 10 + 8))
            MINUTE=$((RANDOM % 60))
            DATE="$(date "+%Y-%m-%d") $HOUR:$(printf "%02d" $MINUTE)"

            echo "Commit $i a las $DATE - $RANDOM" >> "$FILE"
            git add "$FILE"
            git commit -m "Commit automático #$i - $DATE"
          done

          # Push autenticado
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
